### PR TITLE
Travis setup for 5 nodes with tests

### PR DESCRIPTION
**Pull request by AnkshitJain**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
There are a few file missing exceptions in execution node logs. For example, please see [line-2510](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2510). Are these expected?

**Comment by prasadtalasila** [comment]
@AnkshitJain The new code looks good to me.

**Comment by AnkshitJain** [comment]
The file missing exceptions are belong to the [missing file tests](https://github.com/AutolabJS/AutolabJS/blob/dev/tests/functional_tests/missing_files.bats). The first and third test there gives a file missing exception which can be seen at lines [2509](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2509) and [2544](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2544).

**Comment by AnkshitJain** [comment]
To make the tests for concurrent evaluations different from the previous tests, different id numbers have been used. For the 2 concurrent evaluations test, id numbers [2015A7PS101G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2560) and [2015A7PS102G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2645) has been used.
Similarly for 5 concurrent evaluations test, id numbers [2015A7PS201G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2595), [2015A7PS202G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2620), [2015A7PS203G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2570), [2015A7PS204G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2195) and [2015A7PS205G](https://travis-ci.org/AutolabJS/AutolabJS/builds/295732992#L2655) has been used.

**Pull request merged**
