### PR TITLE
Fix issues in deployment tests

### PR DESCRIPTION
**Pull request by AnkshitJain**
## Description
 Fix issues #283, #280, #279 
## Motivation
 Specified in the issues page

 ## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [x] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [x] Read the [contributing guide](https://github.com/AutolabJS/AutolabJS/blob/master/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [x] Avoid other runtime dependencies unless abslutely necessary
 - [x] Rebase your commit history so that each commit is meaningful and states the intention behind the change
 - [x] Ensure that your pull request follows the [style guidelines](https://github.com/AutolabJS/AutolabJS/wiki/Coding-Standards)
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

## Notify reviewers
@prasadtalasila

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@AnkshitJain would it be better to consolidate all the test config into `tests/env.conf` file?

**Comment by AnkshitJain** [comment]
We had decided each test type should have it's own conf file which caters only to the needs of that test module. Hence the need for separate conf files. If we go back to having a single conf file, we only end up making environment variables for test modules that don't require them.

**Comment by prasadtalasila** [comment]
Agreed. It's a trade off we made. I am a bit concerned about the number of locations to change for configuration. Just to run a deployment test for a non-default number (say, eight) execution nodes, the configuration needs to be changed at half a dozen places at least.

This may be for another issue and PR.

On the other hand, `execution_node.bats` assumes that we have at least five execution nodes setup. May not be a bad assumption, but still an assumption.

**Comment by prasadtalasila** [comment]
The PR looks good and runs well even for non-default number execution nodes. I checked for eight execution nodes and it is passing all the tests.

**Pull request merged**
